name: "Workflow for assigning a reviewer if no one has picked up a PR tagged S.toReview after 24 hours"

description: "Checks if the PR needs assignment and assigns someone in a round robin fashion"

inputs:
    repo-token:
        required: true
        description: "Token with permissions to do repo things"

runs:
    using: "node12"
    main: ../../lib/.github/assign_reviewer_main.js
