on:
  workflow_dispatch:
  schedule: 
    - cron: '17 2/3 * * *' # runs every three hours starting from 2 at a random minute to avoid github peaks 
  push: # todo remove this 
    branches:
      - assign-reviewer-fix

jobs: 
  assign-PRs: 
    name: Handle PRs that need to be assigned reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Find PRs and assign reviewers if needed
        uses: ./.github/assign_reviewer
        with: 
          repo-token: ${{secrets.GITHUB_TOKEN}}

      - name: Changes s.ToReview to s.Ongoing if needed (implementation ongoing)