on: 
  check_suite:
    types:
      - completed
  status: 

jobs:
  testjob:
    runs-on: ubuntu-latest
    name: Check if this works
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - run: | 
          echo "toJson(github.event)"

      - run: |
          echo "Check suite completion / status triggered this workflow. Completing..."