on: 
  issue_comment: 
    # todo do it only on created comments --> if not edittinig a comment that has rfr will cause review workflow to run again when not needded?
  # reference for on issue comment https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment

jobs: 
  pr_commented: 
    name: PR Comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if ready for review was commented on PR
        uses: ./.github/ready_for_review # this uses the action file in the stated file to run the workflow
        with: 
          repo-token: ${{secrets.GITHUB_TOKEN}}


# todo obsolete